# 这是一份 Redis 的 WSL 测试环境编排文件。
# 文件保存在 infra/compose/redis 目录下。

services:
  redis:
    image: redis:7.4.7
    container_name: redis7-dev
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

    ports:
      - "0.0.0.0:6379:6379"

    volumes:
      - /data/redis/data:/data
      - ../../../secrets/services/redis/admin.wsl.conf:/usr/local/etc/redis/redis.conf:ro

    networks:
      - zqf_network

networks:
  zqf_network:
    external: true
