from __future__ import annotations

import secrets as secrets_lib
from pathlib import Path
from typing import Any, Callable

TARGET_ALIASES = {
    "wsl": "wsl",
    "prod0-main": "prod0",
}

SUPPORTED_SECRET_TARGETS = tuple(TARGET_ALIASES.keys())


def _target_alias(target: str) -> str:
    return TARGET_ALIASES[target]


def _token() -> str:
    return secrets_lib.token_hex(16)


def _user(prefix: str, target: str) -> str:
    return f"{prefix}_{_target_alias(target)}_{secrets_lib.token_hex(4)}"


def _postgres_admin_user(target: str) -> str:
    if target == "prod0-main":
        return "postgres"
    return _user("pgadmin", target)


def _legacy_postgres_secret_file(repo_root: Path, target: str) -> Path:
    return repo_root / "secrets" / "services" / "postgres" / f"admin.{_target_alias(target)}.env"


def _legacy_redis_secret_file(repo_root: Path, target: str) -> Path:
    return repo_root / "secrets" / "services" / "redis" / f"admin.{_target_alias(target)}.conf"


def _legacy_minio_secret_file(repo_root: Path, target: str) -> Path:
    return repo_root / "secrets" / "services" / "minio" / f"admin.{_target_alias(target)}.env"


def _postgres_env_text(target: str) -> str:
    return (
        f"# Generated by agentplane.cli secrets init-data-services for {target}.\n"
        "POSTGRES_DB=postgres\n"
        f"POSTGRES_USER={_postgres_admin_user(target)}\n"
        f"POSTGRES_PASSWORD={_token()}\n"
    )


def _redis_conf_text(target: str) -> str:
    return (
        f"# Generated by agentplane.cli secrets init-data-services for {target}.\n"
        "bind 0.0.0.0\n"
        "protected-mode yes\n"
        f"requirepass {_token()}\n"
        "port 6379\n"
        "daemonize no\n"
        "dir /data\n"
        "save 900 1\n"
        "save 300 10\n"
        "save 60 10000\n"
        "rdbcompression yes\n"
        "dbfilename dump.rdb\n"
        "appendonly yes\n"
        "appendfilename \"appendonly.aof\"\n"
        "appendfsync everysec\n"
        "loglevel notice\n"
        "logfile \"\"\n"
    )


def _minio_env_text(target: str) -> str:
    return (
        f"# Generated by agentplane.cli secrets init-data-services for {target}.\n"
        f"MINIO_ROOT_USER={_user('minioadmin', target)}\n"
        f"MINIO_ROOT_PASSWORD={_token()}\n"
    )


def _write_secret_file(path: Path, content: str, *, force: bool, role: str | None = None) -> dict[str, str]:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        record = {"path": str(path), "status": "kept"}
        if role:
            record["role"] = role
        return record
    path.write_text(content, encoding="utf-8")
    record = {"path": str(path), "status": "created" if not force else "written"}
    if role:
        record["role"] = role
    return record


def copy_template_file(
    template_path: Path,
    destination: Path,
    *,
    force: bool = False,
    transform: Callable[[str], str] | None = None,
) -> dict[str, str]:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists() and not force:
        return {"template": str(template_path), "path": str(destination), "status": "kept"}
    content = template_path.read_text(encoding="utf-8")
    if transform is not None:
        content = transform(content)
    destination.write_text(content, encoding="utf-8")
    return {
        "template": str(template_path),
        "path": str(destination),
        "status": "written" if force else "created",
    }


def summarize_secret_file(
    path: Path,
    *,
    placeholder_markers: tuple[str, ...] = (),
    required_fragments: tuple[str, ...] = (),
) -> dict[str, Any]:
    if not path.is_file():
        return {"path": str(path), "exists": False, "ok": False, "issues": ["missing"]}
    text = path.read_text(encoding="utf-8")
    issues: list[str] = []
    if any(marker in text for marker in placeholder_markers):
        issues.append("placeholder-values")
    for fragment in required_fragments:
        if fragment not in text:
            issues.append(f"missing-fragment:{fragment}")
    return {"path": str(path), "exists": True, "ok": not issues, "issues": issues}


def _host_truth_root(repo_root: Path, target: str) -> Path:
    return repo_root / "secrets" / "hosts" / target


def _host_infra_secret_file(repo_root: Path, target: str, service: str, filename: str) -> Path:
    return _host_truth_root(repo_root, target) / "infra" / service / filename


def _ensure_host_truth_file(
    truth_path: Path,
    *,
    generated_content: str,
    legacy_projection_path: Path,
    force: bool,
) -> tuple[dict[str, str], str]:
    truth_path.parent.mkdir(parents=True, exist_ok=True)
    if truth_path.exists() and not force:
        return {"path": str(truth_path), "status": "kept", "role": "truth"}, truth_path.read_text(encoding="utf-8")
    if not force and legacy_projection_path.exists():
        migrated_content = legacy_projection_path.read_text(encoding="utf-8")
        truth_path.write_text(migrated_content, encoding="utf-8")
        return {"path": str(truth_path), "status": "migrated", "role": "truth"}, migrated_content
    truth_path.write_text(generated_content, encoding="utf-8")
    return {"path": str(truth_path), "status": "created" if not force else "written", "role": "truth"}, generated_content


def _legacy_runtime_env_path(repo_root: Path, target: str, app_id: str) -> Path:
    alias = _target_alias(target)
    suffix = "wsl" if target == "wsl" else alias
    return repo_root / "secrets" / "services" / f"{app_id}.{suffix}.env"


def _legacy_onepanel_env_path(repo_root: Path, target: str) -> Path:
    if target == "wsl":
        return repo_root / "secrets" / "services" / "onepanel-api.wsl.env"
    return repo_root / "secrets" / "services" / "onepanel-api.env"


def _legacy_backup_env_path(repo_root: Path, target: str) -> Path:
    return repo_root / "secrets" / "services" / f"secrets-backup.r2.{_target_alias(target)}.env"


def _canonical_backup_source_dir(repo_root: Path, target: str) -> str:
    return f"{repo_root}/secrets/hosts/{target}"


def _enforce_env_value(content: str, key: str, value: str) -> str:
    lines = content.splitlines()
    updated = False
    normalized: list[str] = []
    for line in lines:
        if line.startswith(f"{key}="):
            normalized.append(f"{key}={value}")
            updated = True
        else:
            normalized.append(line)
    if not updated:
        normalized.append(f"{key}={value}")
    return "\n".join(normalized).rstrip("\n") + "\n"


def _normalize_backup_env_text(content: str, repo_root: Path, target: str) -> str:
    return _enforce_env_value(content, "SECRETS_BACKUP_SOURCE_DIR", _canonical_backup_source_dir(repo_root, target))


def _copy_projection(
    source: Path,
    target: Path,
    *,
    write: bool,
    transform: Callable[[str], str] | None = None,
) -> dict[str, str]:
    status = "planned"
    target.parent.mkdir(parents=True, exist_ok=True)
    if write:
        content = source.read_text(encoding="utf-8")
        if transform is not None:
            content = transform(content)
        target.write_text(content, encoding="utf-8")
        status = "written"
    return {"source": str(source), "target": str(target), "status": status}


def materialize_legacy_host_layout(repo_root: Path, target: str, *, write: bool) -> dict[str, Any]:
    host_root = _host_truth_root(repo_root, target)
    projections: list[dict[str, str]] = []

    onepanel_source = host_root / "onepanel" / "api.env"
    if onepanel_source.is_file():
        projections.append(_copy_projection(onepanel_source, _legacy_onepanel_env_path(repo_root, target), write=write))

    backup_env_source = host_root / "automations" / "secrets-backup.r2.env"
    if backup_env_source.is_file():
        projections.append(
            _copy_projection(
                backup_env_source,
                _legacy_backup_env_path(repo_root, target),
                write=write,
                transform=lambda content: _normalize_backup_env_text(content, repo_root, target),
            )
        )

    infra_root = host_root / "infra"
    if infra_root.is_dir():
        for service_dir in sorted(path for path in infra_root.iterdir() if path.is_dir()):
            alias = _target_alias(target)
            admin_env = service_dir / "admin.env"
            admin_conf = service_dir / "admin.conf"
            if admin_env.is_file():
                projections.append(
                    _copy_projection(
                        admin_env,
                        repo_root / "secrets" / "services" / service_dir.name / f"admin.{alias}.env",
                        write=write,
                    )
                )
            if admin_conf.is_file():
                projections.append(
                    _copy_projection(
                        admin_conf,
                        repo_root / "secrets" / "services" / service_dir.name / f"admin.{alias}.conf",
                        write=write,
                    )
                )

    apps_root = host_root / "apps"
    if apps_root.is_dir():
        for app_dir in sorted(path for path in apps_root.iterdir() if path.is_dir()):
            runtime_env = app_dir / "runtime.env"
            if runtime_env.is_file():
                projections.append(_copy_projection(runtime_env, _legacy_runtime_env_path(repo_root, target, app_dir.name), write=write))
            tenants_root = app_dir / "tenants"
            if tenants_root.is_dir():
                for tenant_env in sorted(tenants_root.glob("*.env")):
                    projections.append(
                        _copy_projection(
                            tenant_env,
                            repo_root / "secrets" / "tenants" / target / app_dir.name / tenant_env.name,
                            write=write,
                        )
                    )

    ssh_root = host_root / "ssh"
    if ssh_root.is_dir():
        config_file = ssh_root / "config"
        if config_file.is_file():
            projections.append(_copy_projection(config_file, repo_root / "secrets" / "ssh" / "config", write=write))
        keys_root = ssh_root / "keys"
        if keys_root.is_dir():
            for key_file in sorted(path for path in keys_root.rglob("*") if path.is_file()):
                projections.append(
                    _copy_projection(
                        key_file,
                        repo_root / "secrets" / "ssh" / "keys" / key_file.relative_to(keys_root),
                        write=write,
                    )
                )

    return {
        "command": "secrets",
        "action": "sync-host-layout",
        "target": target,
        "ok": True,
        "write": write,
        "projections": projections,
    }


def init_data_services(repo_root: Path, target: str, *, force: bool) -> dict[str, Any]:
    postgres_legacy_path = _legacy_postgres_secret_file(repo_root, target)
    redis_legacy_path = _legacy_redis_secret_file(repo_root, target)
    minio_legacy_path = _legacy_minio_secret_file(repo_root, target)

    postgres_truth, postgres_content = _ensure_host_truth_file(
        _host_infra_secret_file(repo_root, target, "postgres", "admin.env"),
        generated_content=_postgres_env_text(target),
        legacy_projection_path=postgres_legacy_path,
        force=force,
    )
    redis_truth, redis_content = _ensure_host_truth_file(
        _host_infra_secret_file(repo_root, target, "redis", "admin.conf"),
        generated_content=_redis_conf_text(target),
        legacy_projection_path=redis_legacy_path,
        force=force,
    )
    minio_truth, minio_content = _ensure_host_truth_file(
        _host_infra_secret_file(repo_root, target, "minio", "admin.env"),
        generated_content=_minio_env_text(target),
        legacy_projection_path=minio_legacy_path,
        force=force,
    )

    files = [
        postgres_truth,
        _write_secret_file(postgres_legacy_path, postgres_content, force=force, role="projection"),
        redis_truth,
        _write_secret_file(redis_legacy_path, redis_content, force=force, role="projection"),
        minio_truth,
        _write_secret_file(minio_legacy_path, minio_content, force=force, role="projection"),
    ]
    return {
        "command": "secrets",
        "action": "init-data-services",
        "target": target,
        "ok": True,
        "files": files,
    }
